#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_variables)]
#![allow(unused_doc_comments)]
#![allow(unused_mut)]

mod auth;
mod cloud;
mod engine;
mod mcp;
mod onboarding;
mod parser;
mod remediation;
mod reporting;
mod scanner;
mod tui;

// New modules added by CLI overhaul
mod baseline;
mod benchmark;
mod cache;
mod cli;
mod confidence;
mod diff;
mod hook;
mod key_manager;
mod lsp;
mod output;
mod publish;
mod rule_harness;
mod suppression_learner;
mod verification;

use anyhow::Result;
use clap::Parser;
use std::path::PathBuf;

use cli::exit_code::ExitCode;
use cli::{Command, CompletionsArgs, SicarioCli};

fn main() {
    // Silence tracing noise — only show warnings+
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::WARN)
        .init();

    let cli = SicarioCli::parse();

    let result = run(cli);

    match result {
        Ok(code) => std::process::exit(code as i32),
        Err(e) => {
            eprintln!("sicario: {e}");
            std::process::exit(ExitCode::InternalError as i32);
        }
    }
}

fn run(cli: SicarioCli) -> Result<ExitCode> {
    match cli.command {
        None => {
            // Default: scan current directory (headless CLI-first approach)
            let args = cli::scan::ScanArgs::default();
            cmd_scan(args)
        }
        Some(cmd) => dispatch(cmd),
    }
}

fn dispatch(cmd: Command) -> Result<ExitCode> {
    match cmd {
        Command::Scan(args) => cmd_scan(*args),
        Command::Init => {
            let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
            let config_path = cwd.join(".sicario").join("config.yaml");
            if config_path.exists() {
                eprintln!("sicario: .sicario/config.yaml already exists. Skipping init.");
                return Ok(ExitCode::Clean);
            }
            // Detect languages and write a default config
            use onboarding::detector::TechDetector;
            let detector = TechDetector;
            let result = TechDetector::detect(&cwd).unwrap_or_default();
            let languages: Vec<&str> = result.languages.iter().map(|l| l.as_str()).collect();
            std::fs::create_dir_all(cwd.join(".sicario"))?;
            let config_content = format!(
                "# Sicario configuration\n# Generated by `sicario init`\nlanguages:\n{}\n",
                languages
                    .iter()
                    .map(|l| format!("  - {}", l))
                    .collect::<Vec<_>>()
                    .join("\n")
            );
            std::fs::write(&config_path, config_content)?;
            eprintln!(
                "sicario: initialized .sicario/config.yaml (detected: {})",
                if languages.is_empty() {
                    "none".to_string()
                } else {
                    languages.join(", ")
                }
            );
            Ok(ExitCode::Clean)
        }
        Command::Report(args) => {
            cmd_report_handler(&args.dir, args.output.as_deref())?;
            Ok(ExitCode::Clean)
        }
        Command::Fix(args) => cmd_fix(args),
        Command::Baseline(args) => cmd_baseline(args),
        Command::Config(args) => cmd_config(args),
        Command::Suppressions(args) => cmd_suppressions(args),
        Command::Completions(args) => {
            cmd_completions(args);
            Ok(ExitCode::Clean)
        }
        Command::Login => cmd_cloud_login(),
        Command::Logout => cmd_cloud_logout(),
        Command::Publish(args) => cmd_cloud_publish(args.org),
        Command::Whoami => cmd_cloud_whoami(),
        Command::Tui(args) => {
            let scan_dir = PathBuf::from(&args.dir);
            run_interactive_tui(scan_dir)?;
            Ok(ExitCode::Clean)
        }
        Command::Hook(args) => cmd_hook(args),
        Command::Lsp(_args) => {
            let project_root = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
            let rule_paths = crate::lsp::discover_rule_paths(&project_root);
            let server = crate::lsp::SicarioLspServer::new(project_root, rule_paths);
            server.run()?;
            Ok(ExitCode::Clean)
        }
        Command::Benchmark(args) => cmd_benchmark(args),
        Command::Rules(args) => cmd_rules(args),
        Command::Cache(args) => cmd_cache(args),
    }
}

// ─── Scan command ─────────────────────────────────────────────────────────────

fn cmd_scan(args: cli::scan::ScanArgs) -> Result<ExitCode> {
    use cli::exit_code::FindingSummary;
    use cli::scan::OutputFormat;
    use engine::sast_engine::SastEngine;
    use engine::vulnerability::Severity;
    use output::branded::{print_scan_summary, ScanSummary};
    use output::formatter::{render_finding_text, render_findings_table, FormatterConfig};
    use output::sarif::emit_sarif;

    let scan_start = std::time::Instant::now();
    let dir = PathBuf::from(&args.dir);

    let formatter_config = FormatterConfig::from_flags(
        args.no_color,
        args.force_color,
        args.max_lines_per_finding,
        args.max_chars_per_line,
    );

    let explicit: Vec<PathBuf> = args.rules.iter().map(PathBuf::from).collect();
    let rule_files = if explicit.is_empty() {
        discover_bundled_rules()
    } else {
        explicit
    };

    let mut eng = SastEngine::new(&dir)?;
    let mut rules_loaded = 0usize;
    for f in &rule_files {
        if eng.load_rules(f).is_ok() {
            rules_loaded += 1;
        }
    }

    // Count files to scan for the summary
    let mut files_to_scan = Vec::new();
    eng.collect_files_recursive(&dir, &mut files_to_scan)?;
    let files_scanned = files_to_scan.len();
    let total_rules = eng.get_rules().len();

    let mut vulns = eng.scan_directory(&dir)?;
    let scan_duration = scan_start.elapsed();

    // Cloud exposure analysis: auto-detect K8s manifests and adjust priorities
    if !args.no_cloud {
        use cloud::exposure::CloudExposureAnalyzer;
        use cloud::priority::assign_cloud_priority;

        let mut analyzer = CloudExposureAnalyzer::new();
        let mut k8s_found = false;

        // Search for K8s manifest directories
        let k8s_dirs = ["k8s", "kubernetes", "deploy", "manifests", ".k8s"];
        for k8s_dir in &k8s_dirs {
            let candidate = dir.join(k8s_dir);
            if candidate.is_dir() && analyzer.load_kubernetes_configs(&candidate).is_ok() {
                k8s_found = true;
            }
        }

        // Also scan the project root for YAML files with K8s manifests
        if !k8s_found {
            // Check if any YAML files in the root look like K8s manifests
            if analyzer.load_kubernetes_configs(&dir).is_ok() {
                k8s_found = true;
            }
        }

        // Check for CSPM data directories
        let cspm_dirs = ["cspm", ".cspm", "cloud-security"];
        for cspm_dir in &cspm_dirs {
            let candidate = dir.join(cspm_dir);
            if candidate.is_dir() {
                let _ = analyzer.load_cspm_findings(&candidate);
            }
        }

        if k8s_found {
            assign_cloud_priority(&mut vulns, &analyzer);
        }
    }

    // ── SCA: dependency vulnerability scanning ────────────────────────────
    {
        use engine::sca::manifest_parser::ManifestParser;
        use engine::sca::VulnerabilityDatabaseManager;

        let cache_dir = dir.join(".sicario").join("cache");
        match VulnerabilityDatabaseManager::new(&cache_dir) {
            Ok(vuln_db) => {
                // Parse lockfiles/manifests to find all dependencies
                let deps = ManifestParser::parse_directory(&dir).unwrap_or_default();

                if !deps.is_empty() {
                    // Build tuples for the OSV query
                    let dep_tuples: Vec<(String, String, String)> = deps
                        .iter()
                        .filter(|d| !d.version.is_empty())
                        .map(|d| {
                            (
                                d.ecosystem.clone(),
                                d.package_name.clone(),
                                d.version.clone(),
                            )
                        })
                        .collect();

                    // Refresh cache if empty or stale (>24h)
                    if let Ok(true) = vuln_db.is_stale() {
                        if !args.quiet {
                            eprintln!(
                                "sicario: refreshing SCA vulnerability cache from OSV.dev..."
                            );
                        }
                        match vuln_db.refresh_if_stale(&dep_tuples) {
                            Ok(count) => {
                                if !args.quiet && count > 0 {
                                    eprintln!("sicario: cached {} vulnerability records", count);
                                }
                            }
                            Err(e) => {
                                tracing::warn!("SCA cache refresh failed: {}", e);
                                if !args.quiet {
                                    eprintln!("warning: SCA cache refresh failed: {e}");
                                }
                            }
                        }
                    }

                    // Query local cache for each dependency
                    for dep in &deps {
                        if dep.version.is_empty() {
                            continue;
                        }
                        match vuln_db.query_package(&dep.ecosystem, &dep.package_name, &dep.version)
                        {
                            Ok(known_vulns) => {
                                for kv in known_vulns {
                                    let rule_id = format!(
                                        "sca/{}",
                                        kv.cve_id
                                            .as_deref()
                                            .or(kv.ghsa_id.as_deref())
                                            .unwrap_or("unknown")
                                    );
                                    let snippet = format!(
                                        "{}@{} — {}",
                                        dep.package_name, dep.version, kv.summary
                                    );
                                    let mut sca_vuln = engine::vulnerability::Vulnerability::new(
                                        rule_id,
                                        PathBuf::from(format!(
                                            "<{}/{}>",
                                            dep.ecosystem, dep.package_name
                                        )),
                                        0,
                                        0,
                                        snippet,
                                        kv.severity,
                                    );
                                    sca_vuln.owasp_category =
                                        Some(engine::vulnerability::OwaspCategory::A06_VulnerableComponents);
                                    sca_vuln.cwe_id = kv.cve_id.clone();
                                    vulns.push(sca_vuln);
                                }
                            }
                            Err(e) => {
                                tracing::debug!(
                                    "SCA query failed for {}/{}: {}",
                                    dep.ecosystem,
                                    dep.package_name,
                                    e
                                );
                            }
                        }
                    }
                }
            }
            Err(e) => {
                tracing::warn!("Failed to initialize SCA database: {}", e);
                if !args.quiet {
                    eprintln!("warning: SCA scanning unavailable: {e}");
                }
            }
        }
    }

    // Emit primary output in the requested format
    let mut stdout = std::io::stdout();
    match args.format {
        OutputFormat::Json => {
            println!("{}", serde_json::to_string_pretty(&vulns)?);
        }
        OutputFormat::Text => {
            if args.quiet {
                // Quiet mode: just the summary line
            } else {
                output::diagnostics::render_diagnostics(
                    &vulns,
                    formatter_config.color_enabled,
                    &mut stdout,
                )?;
            }
            let summary =
                ScanSummary::from_vulns(&vulns, scan_duration, files_scanned, total_rules);
            print_scan_summary(
                &summary,
                formatter_config.unicode_enabled,
                formatter_config.color_enabled,
                &mut stdout,
            )?;
        }
        OutputFormat::Sarif => {
            let tool_version = env!("CARGO_PKG_VERSION");
            let sarif_doc = emit_sarif(&vulns, tool_version);
            println!("{}", serde_json::to_string_pretty(&sarif_doc)?);
        }
    }

    // Write simultaneous multi-format output to files
    if let Some(ref json_path) = args.json_output {
        let json_str = serde_json::to_string_pretty(&vulns)?;
        std::fs::write(json_path, json_str)?;
        if !args.quiet {
            eprintln!("JSON output written to {json_path}");
        }
    }

    if let Some(ref sarif_path) = args.sarif_output {
        let tool_version = env!("CARGO_PKG_VERSION");
        let sarif_doc = emit_sarif(&vulns, tool_version);
        let sarif_str = serde_json::to_string_pretty(&sarif_doc)?;
        std::fs::write(sarif_path, sarif_str)?;
        if !args.quiet {
            eprintln!("SARIF output written to {sarif_path}");
        }
    }

    if let Some(ref text_path) = args.text_output {
        let mut buf = Vec::new();
        for v in &vulns {
            render_finding_text(v, &formatter_config, &mut buf)?;
        }
        let summary = ScanSummary::from_vulns(&vulns, scan_duration, files_scanned, total_rules);
        print_scan_summary(
            &summary, false, // no unicode in file output
            false, // no color in file output
            &mut buf,
        )?;
        std::fs::write(text_path, buf)?;
        if !args.quiet {
            eprintln!("Text output written to {text_path}");
        }
    }

    // Auto-publish to Sicario Cloud if --publish flag is set
    if args.publish {
        let language_breakdown = build_language_breakdown(&files_to_scan);
        publish_scan_results(
            &vulns,
            scan_duration,
            rules_loaded,
            files_scanned,
            language_breakdown,
            args.org,
        );
    }

    // Compute exit code
    let severity_threshold: Severity = args.severity_threshold.into();
    let summaries: Vec<FindingSummary> = vulns
        .iter()
        .map(|v| FindingSummary {
            severity: v.severity,
            confidence_score: 1.0, // confidence scoring not yet wired
            suppressed: false,     // suppression not yet wired
        })
        .collect();

    Ok(ExitCode::from_findings(
        &summaries,
        severity_threshold,
        args.confidence_threshold,
    ))
}

/// Helper: publish scan results to Sicario Cloud (best-effort, never fails the scan).
fn publish_scan_results(
    vulns: &[engine::vulnerability::Vulnerability],
    scan_duration: std::time::Duration,
    rules_loaded: usize,
    files_scanned: usize,
    language_breakdown: std::collections::HashMap<String, usize>,
    org_id: Option<String>,
) {
    use publish::{
        collect_git_metadata, resolve_cloud_url, PublishClient, ScanMetadata, ScanReport,
    };

    // Check for cloud auth token — silently skip if not authenticated
    let client_id =
        std::env::var("SICARIO_CLOUD_CLIENT_ID").unwrap_or_else(|_| "sicario-cli".to_string());
    let auth_url = std::env::var("SICARIO_CLOUD_AUTH_URL")
        .unwrap_or_else(|_| "https://flexible-terrier-680.convex.site".to_string());

    let auth_module = match auth::auth_module::AuthModule::new(client_id, auth_url) {
        Ok(m) => m,
        Err(_) => {
            eprintln!("warning: --publish skipped (could not initialize auth module)");
            return;
        }
    };

    let token = match auth_module.get_cloud_token() {
        Ok(t) => t,
        Err(_) => {
            eprintln!("warning: --publish skipped (not logged in). Run `sicario login` first.");
            return;
        }
    };

    let (repository, branch, commit_sha) = collect_git_metadata();

    let findings: Vec<engine::vulnerability::Finding> = vulns
        .iter()
        .map(|v| engine::vulnerability::Finding::from_vulnerability(v, &v.rule_id))
        .collect();

    let metadata = ScanMetadata {
        repository,
        branch,
        commit_sha,
        timestamp: chrono::Utc::now(),
        duration_ms: scan_duration.as_millis() as u64,
        rules_loaded,
        files_scanned,
        language_breakdown,
        tags: Vec::new(),
    };

    let report = ScanReport { findings, metadata };
    let cloud_url = resolve_cloud_url();

    let client = match PublishClient::new(cloud_url, token) {
        Ok(c) => c.with_org(org_id),
        Err(e) => {
            eprintln!("warning: --publish skipped ({e})");
            return;
        }
    };

    match client.publish(&report) {
        Ok(resp) => {
            eprintln!(
                "Scan published to Sicario Cloud (scan ID: {}).",
                resp.scan_id
            );
            if let Some(url) = resp.dashboard_url {
                eprintln!("  Dashboard: {url}");
            }
        }
        Err(e) => {
            eprintln!("warning: --publish failed: {e}");
        }
    }
}

/// Build a language breakdown HashMap from file extensions.
///
/// Maps file extension (lowercased, e.g. "rs", "js", "py") to the count of files
/// with that extension. Files without an extension are counted under "other".
fn build_language_breakdown(files: &[PathBuf]) -> std::collections::HashMap<String, usize> {
    let mut breakdown = std::collections::HashMap::new();
    for file in files {
        let ext = file
            .extension()
            .and_then(|e| e.to_str())
            .map(|e| e.to_lowercase())
            .unwrap_or_else(|| "other".to_string());
        *breakdown.entry(ext).or_insert(0) += 1;
    }
    breakdown
}

// ─── Suppressions command ──────────────────────────────────────────────────────

fn cmd_suppressions(args: cli::suppressions::SuppressionsCommand) -> Result<ExitCode> {
    use cli::suppressions::SuppressionsAction;
    use suppression_learner::SuppressionLearner;

    let project_root = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));

    match args.action {
        SuppressionsAction::List => {
            let learner = SuppressionLearner::load(&project_root)?;
            let patterns = learner.list();
            if patterns.is_empty() {
                println!("No learned suppression patterns.");
            } else {
                println!("{:<30} {:<8} Example Snippet", "Rule ID", "Count");
                println!("{}", "-".repeat(70));
                for p in patterns {
                    let snippet_preview: String = p.example_snippet.chars().take(40).collect();
                    println!("{:<30} {:<8} {}", p.rule_id, p.match_count, snippet_preview);
                }
            }
        }
        SuppressionsAction::Reset => {
            let mut learner = SuppressionLearner::load(&project_root)?;
            learner.reset();
            learner.save()?;
            println!("All learned suppression patterns have been cleared.");
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Shell completions ────────────────────────────────────────────────────────

fn cmd_completions(args: CompletionsArgs) {
    use clap::CommandFactory;
    use clap_complete::generate;

    let mut cmd = SicarioCli::command();
    generate(args.shell, &mut cmd, "sicario", &mut std::io::stdout());
}

// ─── Hook command ─────────────────────────────────────────────────────────────

fn cmd_hook(args: cli::hook::HookCommand) -> Result<ExitCode> {
    use cli::hook::HookAction;
    use hook::manager::{HookManagement, HookManager};

    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let mgr = HookManager::new(&cwd)?;

    match args.action {
        HookAction::Install => {
            mgr.install()?;
            eprintln!("sicario: pre-commit hook installed");
        }
        HookAction::Uninstall => {
            mgr.uninstall()?;
            eprintln!("sicario: pre-commit hook uninstalled");
        }
        HookAction::Status => {
            let st = mgr.status()?;
            if st.installed {
                eprintln!("sicario: pre-commit hook is installed");
                if let Some(cmd) = &st.command {
                    eprintln!("  command: {cmd}");
                }
            } else {
                eprintln!("sicario: pre-commit hook is not installed");
            }
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Cloud auth commands ──────────────────────────────────────────────────────

fn cmd_cloud_login() -> Result<ExitCode> {
    let client_id =
        std::env::var("SICARIO_CLOUD_CLIENT_ID").unwrap_or_else(|_| "sicario-cli".to_string());
    let auth_url = std::env::var("SICARIO_CLOUD_AUTH_URL")
        .unwrap_or_else(|_| "https://flexible-terrier-680.convex.site".to_string());

    let auth_module = auth::auth_module::AuthModule::new(client_id, auth_url)?;
    auth_module.cloud_login()?;
    Ok(ExitCode::Clean)
}

fn cmd_cloud_logout() -> Result<ExitCode> {
    let client_id =
        std::env::var("SICARIO_CLOUD_CLIENT_ID").unwrap_or_else(|_| "sicario-cli".to_string());
    let auth_url = std::env::var("SICARIO_CLOUD_AUTH_URL")
        .unwrap_or_else(|_| "https://flexible-terrier-680.convex.site".to_string());

    let auth_module = auth::auth_module::AuthModule::new(client_id, auth_url)?;
    auth_module.cloud_logout()?;
    eprintln!("Logged out of Sicario Cloud.");
    Ok(ExitCode::Clean)
}

fn cmd_cloud_whoami() -> Result<ExitCode> {
    let client_id =
        std::env::var("SICARIO_CLOUD_CLIENT_ID").unwrap_or_else(|_| "sicario-cli".to_string());
    let auth_url = std::env::var("SICARIO_CLOUD_AUTH_URL")
        .unwrap_or_else(|_| "https://flexible-terrier-680.convex.site".to_string());

    let auth_module = auth::auth_module::AuthModule::new(client_id, auth_url)?;
    match auth_module.cloud_whoami() {
        Ok(info) => {
            println!("User:         {}", info.username);
            println!("Email:        {}", info.email);
            println!("Organization: {}", info.organization);
            println!("Plan:         {}", info.plan_tier);
            Ok(ExitCode::Clean)
        }
        Err(e) => {
            eprintln!("sicario whoami: {e}");
            Ok(ExitCode::Clean)
        }
    }
}

fn cmd_cloud_publish(org_id: Option<String>) -> Result<ExitCode> {
    use publish::{
        collect_git_metadata, resolve_cloud_url, PublishClient, ScanMetadata, ScanReport,
    };

    // Check authentication
    let client_id =
        std::env::var("SICARIO_CLOUD_CLIENT_ID").unwrap_or_else(|_| "sicario-cli".to_string());
    let auth_url = std::env::var("SICARIO_CLOUD_AUTH_URL")
        .unwrap_or_else(|_| "https://flexible-terrier-680.convex.site".to_string());

    let auth_module = auth::auth_module::AuthModule::new(client_id, auth_url)?;
    let token = match auth_module.get_cloud_token() {
        Ok(t) => t,
        Err(_) => {
            eprintln!("Not logged in to Sicario Cloud. Run `sicario login` first.");
            return Ok(ExitCode::Clean);
        }
    };

    // Run a scan to get findings
    let scan_start = std::time::Instant::now();
    let dir = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let rule_files = discover_bundled_rules();

    let mut eng = engine::sast_engine::SastEngine::new(&dir)?;
    let mut rules_loaded = 0usize;
    for f in &rule_files {
        if eng.load_rules(f).is_ok() {
            rules_loaded += 1;
        }
    }

    // Collect files to get accurate count and language breakdown
    let mut files_to_scan = Vec::new();
    eng.collect_files_recursive(&dir, &mut files_to_scan)?;
    let files_scanned = files_to_scan.len();
    let language_breakdown = build_language_breakdown(&files_to_scan);

    let vulns = eng.scan_directory(&dir)?;
    let scan_duration = scan_start.elapsed();

    let (repository, branch, commit_sha) = collect_git_metadata();

    let findings: Vec<engine::vulnerability::Finding> = vulns
        .iter()
        .map(|v| engine::vulnerability::Finding::from_vulnerability(v, &v.rule_id))
        .collect();

    let metadata = ScanMetadata {
        repository,
        branch,
        commit_sha,
        timestamp: chrono::Utc::now(),
        duration_ms: scan_duration.as_millis() as u64,
        rules_loaded,
        files_scanned,
        language_breakdown,
        tags: Vec::new(),
    };

    let report = ScanReport { findings, metadata };
    let cloud_url = resolve_cloud_url();
    let client = PublishClient::new(cloud_url, token)?.with_org(org_id);

    match client.publish(&report) {
        Ok(resp) => {
            eprintln!(
                "Scan published to Sicario Cloud (scan ID: {}).",
                resp.scan_id
            );
            if let Some(url) = resp.dashboard_url {
                eprintln!("  Dashboard: {url}");
            }
        }
        Err(e) => {
            eprintln!("sicario publish: {e}");
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Interactive TUI ──────────────────────────────────────────────────────────

fn run_interactive_tui(scan_dir: PathBuf) -> Result<()> {
    use tui::app::{create_tui_channel, SicarioTui};
    use tui::worker::{spawn_scan_worker, ScanJob};

    let (tx, rx) = create_tui_channel();
    let mut app = SicarioTui::new(rx)?;

    // Wire the patch sender so the TUI can apply patches from worker threads
    app.patch_tx = Some(tx.clone());

    // Kick off a background scan immediately so the user sees results fast
    let rule_files = discover_bundled_rules();
    let job = ScanJob {
        directory: scan_dir.clone(),
        rule_files,
    };
    spawn_scan_worker(job, tx.clone());

    // Transition straight to Scanning state — skip the static Welcome screen
    app.state = tui::app::AppState::Scanning {
        progress: 0.0,
        files_scanned: 0,
        total_files: 0,
    };

    // Run the blocking TUI event loop
    let result = app.run();

    // Always restore the terminal even on error
    if let Err(ref e) = result {
        eprintln!("sicario: {e}");
    }

    result
}

// ─── Bundled rule discovery ───────────────────────────────────────────────────

/// Find YAML rule files shipped alongside the binary.
///
/// Search order:
///   1. `<binary_dir>/rules/`
///   2. `<cwd>/sicario-cli/rules/`   (source-tree / dev mode)
///   3. `<cwd>/rules/`
///
/// Searches recursively into subdirectories (e.g. `rules/javascript/*.yaml`).
fn discover_bundled_rules() -> Vec<PathBuf> {
    let mut candidates: Vec<PathBuf> = Vec::new();

    if let Ok(exe) = std::env::current_exe() {
        if let Some(parent) = exe.parent() {
            candidates.push(parent.join("rules"));
        }
    }
    if let Ok(cwd) = std::env::current_dir() {
        candidates.push(cwd.join("sicario-cli").join("rules"));
        candidates.push(cwd.join("rules"));
    }

    for dir in candidates {
        if dir.is_dir() {
            let files = collect_yaml_files_recursive(&dir);
            if !files.is_empty() {
                return files;
            }
        }
    }
    Vec::new()
}

/// Recursively collect all `.yaml` / `.yml` files under `dir`.
fn collect_yaml_files_recursive(dir: &PathBuf) -> Vec<PathBuf> {
    let mut result = Vec::new();
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.filter_map(|e| e.ok()) {
            let path = entry.path();
            if path.is_dir() {
                result.extend(collect_yaml_files_recursive(&path));
            } else if path
                .extension()
                .and_then(|e| e.to_str())
                .map(|e| e == "yaml" || e == "yml")
                .unwrap_or(false)
            {
                result.push(path);
            }
        }
    }
    result
}

// ─── Benchmark command ─────────────────────────────────────────────────────────

fn cmd_benchmark(args: cli::benchmark::BenchmarkArgs) -> Result<ExitCode> {
    use benchmark::BenchmarkRunner;

    let project_root = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let rule_files = discover_bundled_rules();
    let runner = BenchmarkRunner::new(&project_root, rule_files);

    let result = runner.run(&project_root)?;

    // Compare against baseline if requested
    if let Some(ref baseline_name) = args.compare_baseline {
        let baseline = if baseline_name == "latest" {
            runner.load_latest_baseline()?
        } else {
            runner.load_baseline(baseline_name)?
        };

        if let Some(baseline) = baseline {
            let comparison = BenchmarkRunner::compare(&baseline, &result);
            if args.format == "json" {
                println!("{}", serde_json::to_string_pretty(&comparison)?);
            } else {
                print!("{}", comparison.display_text());
            }
            return Ok(ExitCode::Clean);
        } else {
            eprintln!("warning: no baseline found for comparison");
        }
    }

    // Output result
    if args.format == "json" {
        println!("{}", serde_json::to_string_pretty(&result)?);
    } else {
        print!("{}", result.display_text());
    }

    Ok(ExitCode::Clean)
}

// ─── Rules command ────────────────────────────────────────────────────────────

fn cmd_rules(args: cli::rules::RulesCommand) -> Result<ExitCode> {
    use cli::rules::RulesAction;
    use engine::sast_engine::SastEngine;
    use rule_harness::{RuleQualityValidation, RuleTestHarness};

    let project_root = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let rule_files = discover_bundled_rules();

    // Load all rules
    let mut engine = SastEngine::new(&project_root)?;
    for f in &rule_files {
        if let Err(e) = engine.load_rules(f) {
            eprintln!("warning: could not load {:?}: {e}", f);
        }
    }
    let rules = engine.get_rules().to_vec();
    let harness = RuleTestHarness::new(&project_root);

    match args.action {
        RulesAction::Test(test_args) => {
            eprintln!("Running rule test cases for {} rules...", rules.len());
            let report = harness.validate_all(&rules)?;

            if test_args.report {
                if report.aggregate_fp_rate >= 0.15 {
                    eprintln!(
                        "⚠ Aggregate FP rate {:.1}% exceeds 15% threshold",
                        report.aggregate_fp_rate * 100.0
                    );
                }
                println!("{}", serde_json::to_string_pretty(&report)?);
            } else {
                print!("{}", report.display_text());
            }

            if report.invalid_rules > 0 {
                return Ok(ExitCode::FindingsDetected);
            }
        }
        RulesAction::Validate(validate_args) => {
            eprintln!("Validating {} rules...", rules.len());
            let report = harness.validate_all_syntax(&rules);

            if validate_args.report {
                println!("{}", serde_json::to_string_pretty(&report)?);
            } else {
                print!("{}", report.display_text());
            }

            if report.invalid_rules > 0 {
                return Ok(ExitCode::FindingsDetected);
            }
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Fix command ──────────────────────────────────────────────────────────────

fn cmd_fix(args: cli::fix::FixArgs) -> Result<ExitCode> {
    use remediation::remediation_engine::RemediationEngine;
    use verification::scanner::VerificationScanning;

    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));

    // Handle revert
    if let Some(ref patch_id) = args.revert {
        let engine = RemediationEngine::new(&cwd)?;
        engine.revert_by_patch_id(patch_id)?;
        eprintln!("sicario: reverted patch {patch_id}");
        return Ok(ExitCode::Clean);
    }

    let file_path = PathBuf::from(&args.file);
    if !file_path.exists() {
        eprintln!("sicario fix: file not found: {}", args.file);
        return Ok(ExitCode::InternalError);
    }

    // Scan the file to find vulnerabilities
    let mut eng = engine::sast_engine::SastEngine::new(&cwd)?;
    for f in discover_bundled_rules() {
        let _ = eng.load_rules(&f);
    }
    let vulns = eng.scan_directory(file_path.parent().unwrap_or(&cwd))?;

    // Filter to the target file and optionally the specified rule
    let file_vulns: Vec<_> = vulns
        .iter()
        .filter(|v| v.file_path == file_path)
        .filter(|v| args.rule.as_ref().is_none_or(|r| v.rule_id == *r))
        .collect();

    if file_vulns.is_empty() {
        eprintln!("sicario fix: no findings in {}", args.file);
        return Ok(ExitCode::Clean);
    }

    let engine = RemediationEngine::new(&cwd)?;
    for vuln in &file_vulns {
        let patch = engine.generate_patch(vuln)?;
        let confirmed = engine.display_diff_and_confirm(&patch)?;
        if confirmed {
            engine.apply_patch(&patch)?;
            eprintln!("sicario: patch applied to {}", args.file);

            // Post-fix verification
            if !args.no_verify {
                let mut verifier = verification::VerificationScanner::new(&cwd);
                let original = verification::OriginalFinding {
                    rule_id: vuln.rule_id.clone(),
                    fingerprint: engine::vulnerability::Finding::compute_fingerprint(
                        &vuln.rule_id,
                        &vuln.file_path,
                        &vuln.snippet,
                    ),
                    file_path: vuln.file_path.clone(),
                };
                let rule_files = discover_bundled_rules();
                match verifier.verify_fix(&file_path, &original, &rule_files)? {
                    verification::VerificationResult::Resolved => {
                        eprintln!("sicario: fix verified — vulnerability resolved");
                    }
                    verification::VerificationResult::StillPresent => {
                        eprintln!("sicario: warning — vulnerability still present after fix");
                    }
                    verification::VerificationResult::NewFindingsIntroduced(new) => {
                        eprintln!(
                            "sicario: warning — fix introduced {} new finding(s)",
                            new.len()
                        );
                    }
                }
            }
        } else {
            eprintln!("sicario: patch skipped");
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Baseline command ─────────────────────────────────────────────────────────

fn cmd_baseline(args: cli::baseline::BaselineCommand) -> Result<ExitCode> {
    use baseline::manager::{BaselineManagement, BaselineManager};
    use cli::baseline::BaselineAction;

    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let mgr = BaselineManager::new(&cwd);

    match args.action {
        BaselineAction::Save(save_args) => {
            // Run a scan to get current findings
            let rule_files = discover_bundled_rules();
            let mut eng = engine::sast_engine::SastEngine::new(&cwd)?;
            for f in &rule_files {
                let _ = eng.load_rules(f);
            }
            let vulns = eng.scan_directory(&cwd)?;
            let findings: Vec<engine::vulnerability::Finding> = vulns
                .iter()
                .map(|v| engine::vulnerability::Finding::from_vulnerability(v, &v.rule_id))
                .collect();

            let path = mgr.save(&findings, save_args.tag.as_deref())?;
            eprintln!("sicario: baseline saved to {}", path.display());
        }
        BaselineAction::Compare(cmp_args) => {
            // Run a scan to get current findings
            let rule_files = discover_bundled_rules();
            let mut eng = engine::sast_engine::SastEngine::new(&cwd)?;
            for f in &rule_files {
                let _ = eng.load_rules(f);
            }
            let vulns = eng.scan_directory(&cwd)?;
            let findings: Vec<engine::vulnerability::Finding> = vulns
                .iter()
                .map(|v| engine::vulnerability::Finding::from_vulnerability(v, &v.rule_id))
                .collect();

            let delta = mgr.compare(&cmp_args.reference, &findings)?;
            if cmp_args.format == "json" {
                println!("{}", serde_json::to_string_pretty(&delta)?);
            } else {
                eprintln!(
                    "New: {}  Resolved: {}  Unchanged: {}",
                    delta.new_findings.len(),
                    delta.resolved_findings.len(),
                    delta.unchanged_findings.len()
                );
            }
        }
        BaselineAction::Trend(trend_args) => {
            let summaries = mgr.trend()?;
            if trend_args.format == "json" {
                println!("{}", serde_json::to_string_pretty(&summaries)?);
            } else {
                for s in &summaries {
                    eprintln!(
                        "{} {}: {} findings (C:{} H:{} M:{} L:{} I:{})",
                        s.timestamp.format("%Y-%m-%d %H:%M"),
                        s.tag.as_deref().unwrap_or("-"),
                        s.total_findings,
                        s.critical_count,
                        s.high_count,
                        s.medium_count,
                        s.low_count,
                        s.info_count,
                    );
                }
            }
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Config command ───────────────────────────────────────────────────────────

fn cmd_config(args: cli::config::ConfigCommand) -> Result<ExitCode> {
    use cli::config::ConfigAction;

    match args.action {
        ConfigAction::SetKey => {
            eprintln!("Enter your LLM API key: ");
            let mut key = String::new();
            std::io::stdin().read_line(&mut key)?;
            let key = key.trim();
            if key.is_empty() {
                eprintln!("sicario config: no key provided");
                return Ok(ExitCode::Clean);
            }
            key_manager::store_key_in_keyring(key)?;
            eprintln!("sicario: API key stored in OS credential store");
        }
        ConfigAction::SetProvider(provider_args) => {
            let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
            let config_dir = cwd.join(".sicario");
            std::fs::create_dir_all(&config_dir)?;
            let config_path = config_dir.join("config.yaml");

            let model = provider_args
                .model
                .unwrap_or_else(|| "gpt-4o-mini".to_string());
            let content = format!(
                "# Sicario LLM provider config\nendpoint: \"{}\"\nmodel: \"{}\"\n",
                provider_args.endpoint, model
            );
            std::fs::write(&config_path, content)?;
            eprintln!(
                "sicario: provider set to {} (model: {})",
                provider_args.endpoint, model
            );
        }
        ConfigAction::Show => {
            let endpoint = key_manager::resolve_endpoint();
            let model = key_manager::resolve_model();
            let key_info = key_manager::resolve_api_key();
            let key_source = key_info
                .map(|k| k.source.label().to_string())
                .unwrap_or_else(|| "not configured".to_string());

            println!("Endpoint: {endpoint}");
            println!("Model:    {model}");
            println!("API Key:  {key_source}");
        }
        ConfigAction::DeleteKey => {
            key_manager::delete_key_from_keyring()?;
            eprintln!("sicario: API key removed from OS credential store");
        }
        ConfigAction::Test => {
            let key = key_manager::resolve_api_key();
            if key.is_none() {
                eprintln!(
                    "sicario config test: no API key configured. Run `sicario config set-key`."
                );
                return Ok(ExitCode::Clean);
            }
            let endpoint = key_manager::resolve_endpoint();
            let model = key_manager::resolve_model();
            eprintln!("Testing connectivity to {endpoint} with model {model}...");
            // Simple connectivity check via reqwest
            let client = reqwest::blocking::Client::builder()
                .timeout(std::time::Duration::from_secs(10))
                .build()?;
            let key = key.unwrap();
            let resp = client
                .post(&endpoint)
                .header("Authorization", format!("Bearer {}", key.key))
                .header("Content-Type", "application/json")
                .body(format!(
                    r#"{{"model":"{}","messages":[{{"role":"user","content":"ping"}}],"max_tokens":1}}"#,
                    model
                ))
                .send();
            match resp {
                Ok(r) if r.status().is_success() => {
                    eprintln!(
                        "sicario: connection successful (key source: {})",
                        key.source.label()
                    );
                }
                Ok(r) => {
                    eprintln!("sicario: server responded with status {}", r.status());
                }
                Err(e) => {
                    eprintln!("sicario: connection failed: {e}");
                }
            }
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Cache command ────────────────────────────────────────────────────────────

fn cmd_cache(args: cli::cache::CacheCommand) -> Result<ExitCode> {
    use cache::scan_cache::ScanCaching;
    use cache::ScanCache;
    use cli::cache::CacheAction;

    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    let mut cache = ScanCache::new(&cwd)?;

    match args.action {
        CacheAction::Clear => {
            cache.clear()?;
            eprintln!("sicario: scan cache cleared");
        }
        CacheAction::Stats => {
            let stats = cache.stats()?;
            println!("Cached files: {}", stats.cached_files);
            println!("Size:         {} bytes", stats.size_bytes);
            if let Some(oldest) = stats.oldest_entry {
                println!("Oldest entry: {}", oldest.format("%Y-%m-%d %H:%M:%S"));
            }
        }
    }

    Ok(ExitCode::Clean)
}

// ─── Report handler (preserved from original) ────────────────────────────────

fn cmd_report_handler(dir_str: &str, output: Option<&str>) -> Result<()> {
    use engine::sast_engine::SastEngine;
    use reporting::{generate_compliance_report, write_compliance_reports};

    let dir = PathBuf::from(dir_str);
    let output_dir = output
        .map(PathBuf::from)
        .unwrap_or_else(|| dir.join(".sicario").join("reports"));

    let mut eng = SastEngine::new(&dir)?;
    for f in discover_bundled_rules() {
        if let Err(e) = eng.load_rules(&f) {
            eprintln!("warning: could not load {:?}: {e}", f);
        }
    }

    let vulns = eng.scan_directory(&dir)?;
    let report = generate_compliance_report(&vulns);
    let (json_path, md_path) = write_compliance_reports(&report, &output_dir)?;

    println!("OWASP report: {}", json_path.display());
    println!("Markdown:     {}", md_path.display());
    println!(
        "Total: {}  |  Categories affected: {}/10",
        report.total_vulnerabilities, report.categories_affected
    );
    Ok(())
}
