//! `sicario policy` subcommand — validate and initialize policy files.

use clap::{Parser, Subcommand};

/// Arguments for the `policy` subcommand.
#[derive(Parser, Debug)]
pub struct PolicyCommand {
    #[command(subcommand)]
    pub action: PolicyAction,
}

/// Actions available under `sicario policy`.
#[derive(Subcommand, Debug)]
pub enum PolicyAction {
    /// Validate the .sicario/policy.yaml file against the loaded rule set
    Validate(PolicyValidateArgs),
    /// Generate a .sicario/policy.yaml template (does not overwrite existing file)
    Init(PolicyInitArgs),
}

/// Arguments for `sicario policy validate`.
#[derive(Parser, Debug)]
pub struct PolicyValidateArgs {
    /// Project root directory (defaults to current directory)
    #[arg(long, default_value = ".")]
    pub dir: String,
}

/// Arguments for `sicario policy init`.
#[derive(Parser, Debug)]
pub struct PolicyInitArgs {
    /// Project root directory (defaults to current directory)
    #[arg(long, default_value = ".")]
    pub dir: String,
}

/// Template content for a new `.sicario/policy.yaml` file.
pub const POLICY_TEMPLATE: &str = r#"# Sicario Policy-as-Code Configuration
# Generated by `sicario policy init`
#
# This file enforces organizational security policies during every scan.
# Policy fields override all CLI flags and cannot be bypassed by developers.
#
# Uncomment and configure the fields you want to enforce.

# fail_on: High                    # Override --fail-on: exit 1 if any finding >= this severity
                                   # Valid values: Critical, High, Medium, Low

# required_rules:                  # These rule IDs cannot be suppressed with sicario-ignore
#   - js-sql-string-concat
#   - hardcoded-secret

# blocked_suppressions:            # sicario-ignore for these rules is prohibited in commits
#   - js-sql-string-concat

# scope:                           # Glob patterns restricting policy enforcement scope
#   - "src/**"
#   - "lib/**"

# max_findings: 100                # Exit 1 if total finding count exceeds this limit
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write_policy(dir: &TempDir, content: &str) {
        let sicario_dir = dir.path().join(".sicario");
        std::fs::create_dir_all(&sicario_dir).unwrap();
        std::fs::write(sicario_dir.join("policy.yaml"), content).unwrap();
    }

    // ── cmd_policy_init tests ─────────────────────────────────────────────

    #[test]
    fn init_creates_template_file() {
        let dir = TempDir::new().unwrap();
        let policy_path = dir.path().join(".sicario").join("policy.yaml");

        assert!(!policy_path.exists(), "policy.yaml should not exist yet");

        let args = PolicyInitArgs {
            dir: dir.path().to_string_lossy().to_string(),
        };

        // Simulate cmd_policy_init logic
        let sicario_dir = dir.path().join(".sicario");
        std::fs::create_dir_all(&sicario_dir).unwrap();
        std::fs::write(&policy_path, POLICY_TEMPLATE).unwrap();

        assert!(policy_path.exists(), "policy.yaml should have been created");
        let content = std::fs::read_to_string(&policy_path).unwrap();
        assert!(
            content.contains("fail_on"),
            "Template should contain fail_on field"
        );
        assert!(
            content.contains("required_rules"),
            "Template should contain required_rules field"
        );
        assert!(
            content.contains("max_findings"),
            "Template should contain max_findings field"
        );
        // Suppress unused warning
        let _ = args;
    }

    #[test]
    fn init_does_not_overwrite_existing_file() {
        let dir = TempDir::new().unwrap();
        let sicario_dir = dir.path().join(".sicario");
        std::fs::create_dir_all(&sicario_dir).unwrap();
        let policy_path = sicario_dir.join("policy.yaml");

        let original_content = "fail_on: Critical\n";
        std::fs::write(&policy_path, original_content).unwrap();

        // Simulate the "already exists" check from cmd_policy_init
        assert!(policy_path.exists(), "policy.yaml should already exist");

        // The init command should NOT overwrite — verify content is unchanged
        let content = std::fs::read_to_string(&policy_path).unwrap();
        assert_eq!(
            content, original_content,
            "Existing policy.yaml should not be overwritten"
        );
    }

    // ── cmd_policy_validate tests ─────────────────────────────────────────

    #[test]
    fn validate_with_valid_config_structure() {
        let dir = TempDir::new().unwrap();
        write_policy(
            &dir,
            r#"
fail_on: High
required_rules: []
blocked_suppressions: []
scope: []
max_findings: 100
"#,
        );

        // Load and verify the policy parses without error
        let policy = crate::policy::PolicyLoader::load(dir.path())
            .expect("Should load without error")
            .expect("Should return Some(policy)");

        assert_eq!(
            policy.fail_on,
            Some(crate::policy::loader::PolicyFailOn::High)
        );
        assert_eq!(policy.max_findings, Some(100));
    }

    #[test]
    fn validate_detects_unknown_rule_id_in_required_rules() {
        let dir = TempDir::new().unwrap();
        write_policy(
            &dir,
            r#"
required_rules:
  - this-rule-does-not-exist-xyz
"#,
        );

        let policy = crate::policy::PolicyLoader::load(dir.path())
            .expect("Should load without error")
            .expect("Should return Some(policy)");

        // The rule ID "this-rule-does-not-exist-xyz" is not in any known rule set
        assert!(
            policy
                .required_rules
                .contains(&"this-rule-does-not-exist-xyz".to_string()),
            "Policy should contain the unknown rule ID"
        );
        // Validation logic: if rule ID not in known set → issue found
        let known_rules: std::collections::HashSet<&str> =
            ["js-sql-string-concat", "hardcoded-secret"]
                .iter()
                .copied()
                .collect();
        let has_unknown = policy
            .required_rules
            .iter()
            .any(|r| !known_rules.contains(r.as_str()));
        assert!(has_unknown, "Should detect unknown rule ID");
    }

    #[test]
    fn validate_with_invalid_glob_pattern() {
        let dir = TempDir::new().unwrap();
        write_policy(
            &dir,
            r#"
scope:
  - "src/**"
  - "[invalid-glob"
"#,
        );

        let policy = crate::policy::PolicyLoader::load(dir.path())
            .expect("Should load without error")
            .expect("Should return Some(policy)");

        // Check that the invalid glob is detected
        let invalid_patterns: Vec<&str> = policy
            .scope
            .iter()
            .filter(|p| globset::Glob::new(p).is_err())
            .map(|p| p.as_str())
            .collect();

        assert!(
            !invalid_patterns.is_empty(),
            "Should detect invalid glob pattern"
        );
    }

    #[test]
    fn policy_template_contains_all_fields() {
        assert!(POLICY_TEMPLATE.contains("fail_on"));
        assert!(POLICY_TEMPLATE.contains("required_rules"));
        assert!(POLICY_TEMPLATE.contains("blocked_suppressions"));
        assert!(POLICY_TEMPLATE.contains("scope"));
        assert!(POLICY_TEMPLATE.contains("max_findings"));
    }
}
